// Yimeng: the pixel rig (head, torso, arms, legs) and every outfit in the spec's wardrobe.
// Ported from the approved mockup (.superpowers/pixel-mock/art_a.py + art_wear.py); the
// golden test in tests/reel/hero.test.js holds this file to those exact pixels.
import { Grid, parseRows, line, recolor } from './pixels.js';

export const SPRITE_W = 42, SPRITE_H = 50;
export const ANCHOR_X = 9;            // the character's left edge inside the sprite
export const FOOT_Y = 44;             // the row the shoes stand on (rig y 33 + offset 11)
const OX = 9, OY = 11;

export const BASE_PALETTE = {
  k: '#2a1f2d', H: '#25212c', h: '#4a4458', f: '#4a4352', e: '#f0c39f', q: '#c98d6e',
  S: '#f4cfae', s: '#e0a985', o: '#b5735a', G: '#3a2419', g: '#ffffff', E: '#241c22',
  m: '#c46a5e', Y: '#eef1f6', B: '#8a2438', b: '#5e1727', r: '#ad4357', T: '#1e1c24',
  P: '#3e4262', p: '#2b2d46', l: '#50557c', O: '#17151b', n: '#4d4856',
};
// Colours every outfit can rely on for props and hats unless it overrides them.
const PROP_DEFAULTS = {
  x: '#22232b', M: '#3b404c', m: '#2a2e37', V: '#d9a35b', v: '#a87e3e', K: '#1c1c22',
  J: '#3b404c', j: '#2a2e37', Z: '#e08a2c', z: '#b06a1e', F: '#16181e', a: '#bfe3f2',
};

// ---------- rig ----------
const HEAD = `
...........HHH......
.......HHHHHHHHH....
.....HHHHHHHHHhhH...
....HHHHHHHHHHHHHH..
...HHHHHHHHHHHHHHHH.
...HHHHHHHHHHHHHHHH.
..fHHHHHHHHHHHHHHHS.
..ffHHHHHHHHHHHSSSS.
..fffHHHHHHSSSSSSSS.
..ffffeeSSSSSSSSSSS.
..fffeqeSSSSSSSSSSSS
..ffffeSSSSSSSSSSSS.
...fffSSSSSSSSSSSSs.
....ffSSSSSSSSSSSs..
......sSSSSSSSSss...
`;
const FACE = `
....................
....................
....................
....................
....................
....................
....................
....................
.............GGGGG..
........GGGGGGgSEG..
.............GSSEG..
.............GGGGG..
......Y.............
.................m..
....................
`;
const ARMS = {
  mid: `
.......BB...........
.......Br...........
.......Br...........
.......BB...........
.......SS...........
`,
  fwd: `
.......BB...........
.......BBr..........
........BBr.........
........BBB.........
.........SS.........
`,
  back: `
.......BB...........
......rBB...........
......rBB...........
......BBB...........
......SS............
`,
};
ARMS.curlDown = ARMS.mid;             // a dumbbell curl: the arm hangs, then the forearm comes up
ARMS.curlUp = `
.......BB.SS........
.......BBBr.........
.......BBBr.........
.......BBB..........
`;
const ARM_HOLD = `
.......BB...........
.......BBr..........
.......BBBBSS.......
`;
const ARM_BIG = {
  mid: `
.....SSSSS..........
.....SSSSs..........
......SSSs..........
......SSSs..........
.......SS...........
`,
  fwd: `
......SSSS..........
.......SSSs.........
........SSSs........
........SSS.........
.........SS.........
`,
  back: `
......SSSS..........
.....sSSS...........
.....sSSS...........
.....sSS............
......SS............
`,
};
ARM_BIG.curlDown = ARM_BIG.mid;
ARM_BIG.curlUp = `
.....SSSS.SSS.......
.....SSSSSSSSs......
.....sSSSSSSs.......
......sSSSs.........
`;
const LEGS = {
  pass: `
......ppPPPP........
.......ppPPl........
.......ppPPl........
.......ppPPl........
......pp.PPl........
.....OnO.PPl........
.........OOnOO......
.........OOOOO......
`,
  near: `
......ppPPPP........
......pp..PPl.......
......pp..PPl.......
.....pp....PPl......
.....pp....PPl......
....pp......PPl.....
...OnO......OOOnO...
...OO.......OOOOO...
`,
  far: `
......PPpppp........
......PPl..pp.......
......PPl..pp.......
.....PPl....pp......
.....PPl....pp......
....PPl......pp.....
...OOnO......OOnOO..
...OOOO......OOOOO..
`,
  // seated on a ledge, legs dangling over its edge; two frames swing the shins
  sitA: `
......ppPPPPPPPP....
......ppPPPPPPPl....
............pPPl....
............pPPl....
............pPPl....
...........OOOnO....
...........OOOOOO...
`,
  sitB: `
......ppPPPPPPPP....
......ppPPPPPPPl....
............pPPl....
.............pPPl...
.............pPPl...
............OOOnO...
............OOOOOO..
`,
  stand: `
......ppPPPP........
......pp.PPl........
......pp.PPl........
......pp.PPl........
......pp.PPl........
......pp.PPl........
.....OOO.OOOOO......
.....OOO.OOOOO......
`,
};

// ---------- torsos (8 rows, x5..12) and skirts (over the legs) ----------
const T = {
  blazer: `
......bBBBTT........
.....bBBBBBTT.......
.....bBBBBrTT.......
.....bBBBBrTB.......
.....bBBBBBTB.......
.....bBBBBBBB.......
.....bbBBBBBB.......
......PPPPPP........
`,
  hoodie: `
......BBBBBB........
.....bBBBBBBw.......
.....bBBBBBBw.......
.....bBBBBBBB.......
.....bBBbbbbB.......
.....bBBBBBBB.......
.....bbbbbbbb.......
......PPPPPP........
`,
  sunhood: `
......BBBBBB........
.....bBBBBBBz.......
.....bBBBBBBz.......
.....bBBBBBBz.......
.....bBBBBBBz.......
.....bBBBBBBz.......
.....bbbbbbbz.......
......PPPPPP........
`,
  puffer: `
.....bBBBBBBB.......
....bBBBBBBBBB......
....bbbbbbbbbb......
....bBBBBBBBBB......
....bbbbbbbbbb......
....bBBBBBBBBB......
....bbbbbbbbbb......
......PPPPPP........
`,
  tank: `
......sSBBBS........
.....sSSBBBBS.......
.....sSBBBBBB.......
.....bBBBBBBB.......
.....bBBBBBBB.......
.....bBBBBBBB.......
.....bbBBBBBB.......
......PPPPPP........
`,
  tankBig: `
....sSSSBBBBSS......
...sSSSSBBBBBSS.....
...sSSBBBBBBBBB.....
....bBBBBBBBBBB.....
.....bBBBBBBBBB.....
.....bBBBBBBBB......
......bBBBBBB.......
......PPPPPP........
`,
  shell: `
......BBBBTT........
.....bBBBBBrT.......
.....bBBBBBrB.......
.....bBBBBBrB.......
.....bBBBBBrB.......
.....bBBBBBrB.......
.....bbbbbbbb.......
......PPPPPP........
`,
  vest: `
......TTTTTT........
.....tTBBTBBT.......
.....tBBBBBBB.......
.....tBbbBbbB.......
.....tBBBBBBB.......
.....tBbbBbbB.......
.....ttBBBBBB.......
......PPPPPP........
`,
  bib: `
......TTTTTT........
.....tTTBTTTT.......
.....tTTBTTTT.......
.....bBBBBBBB.......
.....bBBBBBBB.......
.....bBBBBBBB.......
.....bBBBBBBB.......
......PPPPPP........
`,
  wetsuit: `
......BBBBBB........
.....bBBBBBBB.......
.....bBBBBBBB.......
.....bBBBBBBB.......
.....brrrrrrB.......
.....bBBBBBBB.......
.....bbBBBBBB.......
......PPPPPP........
`,
  gown: `
......BBBBBB........
.....bBBBBBrB.......
.....bBBBBBrB.......
.....bBBBBBrB.......
.....bBBBBBrB.......
.....bBBBBBrB.......
.....bBBBBBrB.......
.....bBBBBBBB.......
`,
  phd: `
......BBBBBB........
.....bBBBBBKB.......
.....bBBBBBKB.......
.....bBBBBBKB.......
.....bBBBBBKB.......
.....bBBBBBKB.......
.....bBBBBBKB.......
.....bBBBBBKB.......
`,
  coat: `
......bBBBTT........
.....bBBBBBTT.......
.....bBBBBrTT.......
.....bBBBBrBB.......
.....bBBBBrBB.......
.....bBBBBBBB.......
.....bbbbbbbb.......
.....bBBBBBBB.......
`,
};
const SKIRT = {
  gown: `
.....bBBBBBrBB......
.....bBBBBBrBB......
....bBBBBBBrBBB.....
....bBBBBBBrBBB.....
....bbBBBBBBBBB.....
`,
  phd: `
.....bBBBBBKBB......
.....bBBBBBKBB......
....bBBBBBBKBBB.....
....bBBBBBBKBBB.....
....bbBBBBBBBBB.....
`,
  coat: `
.....bBBBBBBB.......
.....bBBBBBBB.......
.....bbBBBBBB.......
`,
};
const HOOD = `
.BB.
BBBB
bBBB
`;

// ---------- hats (head-grid coordinates) ----------
const HAT = {
  beanie: `
.....JJJJJJJJJ......
...JJJJJJJJJJJJJ....
..JJJJJJJJJJJJJJJ...
..JJJJJJJJJJJJJJJJ..
..JJJJJJJJJJJJJJJJ..
..jjjjjjjjjjjjjjjjj.
`,
  cap: `
.......JJJJJ........
.....JJJJJJJJJ......
....JJJJJJJJJJJJ....
...JJJJJJJJJJJJJJ...
...JJJJJJJJJJJJJJJ..
..JJJJJJJJJJjjjjjjjjj
`,
  mortar: `
..JJJJJJJJJJJJJJJJJJ
.jjjjjjjjjjjjjjjjjj.
.....JJJJJJJJJJ.....
....JJJJJJJJJJJJ....
...JJJJJJJJJJJJJJ...
...jJJJJJJJJJJJJJJ..
`,
  tam: `
......KKKKKKK.......
...KKKKKKKKKKKKK....
..KKKKKKKKKKKKKKKK..
..KKKKKKKKKKKKKKKK..
...KKKKKKKKKKKKKKK..
`,
  bucket: `
.......JJJJJJ.......
.....JJJJJJJJJJ.....
....JJJJJJJJJJJJ....
....jjjjjjjjjjjj....
.JJJJJJJJJJJJJJJJJJJ
JJ.................JJ
`,
};
const POM = `
.........VVV........
........VVVVV.......
.........VVV........
`;

// ---------- props ----------
const PROP = {
  backpack: `
.MMMM.
MMMMMm
MMMMMm
MmmmMm
MMMMMm
MMMMMm
.mmmm.
`,
  bigpack: `
.ZZZZZ.
.zzzzz.
MMMMMMm
MMMMMMm
MmmmmMm
MMMMMMm
MMMMMMm
MMMMMMm
MMMMMMm
.mmmmm.
`,
  tank: `
.xx.
VVVV
VVVv
VVVv
VVVv
VVVv
VVVv
VVVv
VVVv
.vv.
`,
  umbrella: `
........VVVVV........
.....VVVVVVVVVVV.....
...VVVVVVVVVVVVVVV...
..VVVVVVVVVVVVVVVVV..
.VVVVVVVVVVVVVVVVVVV.
VvVVvVVvVVvVVvVVvVVvV
`,
  basket: `
.x...x.
.xxxxx.
ZzZZzZZ
MMMMMMM
MmMmMmM
.MMMMM.
`,
  bucket: `
.xxxxx.
x.ZZZ.x
MMMMMMM
MMMMMMM
.MMMMM.
`,
};

// ---------- the wardrobe ----------
// props: [kind, part, dx, dy]; kinds: back, umbrella, hand, camera, rod, gun.
export const OUTFITS = {
  sheffield: { torso: 'hoodie', hold: true, props: [['back', 'backpack', 2, 18], ['umbrella', 'umbrella', 1, -6]],
    pal: { B: '#5a3a9a', b: '#3e2672', w: '#e9e4f5', P: '#3d5c8c', p: '#2c4468', l: '#5677a8', O: '#e7e2d8', n: '#bdb7aa', M: '#3b404c', m: '#2a2e37', V: '#24324f', v: '#3b4c72', x: '#20232b' } },
  travel: { torso: 'blazer', props: [['back', 'backpack', 2, 18], ['camera', null, 0, 0]],
    pal: { B: '#4f6f9f', b: '#3a5480', r: '#6d8dbd', T: '#efebe2', P: '#c9b48e', p: '#a8946f', l: '#ddc9a3', O: '#e7e2d8', n: '#bdb7aa', M: '#7a5a3e', m: '#5c4330' } },
  trolltunga: { torso: 'shell', props: [['back', 'bigpack', 1, 14]],
    pal: { B: '#c8402e', b: '#8f2a1e', r: '#e2604a', T: '#2a2a30', P: '#5b6170', p: '#454a57', l: '#737a8a', O: '#5a3b2a', n: '#7a5440', M: '#3d4350', m: '#2b2f39', Z: '#e08a2c', z: '#b06a1e' } },
  iceland: { torso: 'puffer', hats: ['beanie'],
    pal: { B: '#2c3a5c', b: '#1f2a44', P: '#2b2d36', p: '#1f2028', l: '#3a3d4a', O: '#3a2c24', n: '#5a463a', J: '#d8a531', j: '#a87e1e' } },
  nyc: { torso: 'coat', skirt: 'coat', scarf: true,
    pal: { B: '#b38a5c', b: '#8a6642', r: '#cfa676', T: '#2a2a30', P: '#24242c', p: '#18181e', l: '#33333d', O: '#1a1416', n: '#3a2c2c', L: '#6b2a3a', Q: '#8a3a4c' } },
  michelin: { torso: 'blazer', pal: {} },
  columbia: { torso: 'gown', skirt: 'gown', sleeve: { B: 'B', b: 'b', r: 'r' }, hats: ['mortar'], tassel: 'V',
    pal: { B: '#9cc7ea', b: '#6f9fca', r: '#c3def3', J: '#9cc7ea', j: '#6f9fca', V: '#f4f1ea', P: '#24242c', p: '#18181e', l: '#33333d', O: '#1a1416', n: '#3a2c2c' } },
  mi_winter: { torso: 'puffer', hats: ['beanie'], pom: true,
    pal: { B: '#1f5a46', b: '#16463a', P: '#2b2d36', p: '#1f2028', l: '#3a3d4a', O: '#3a2c24', n: '#5a463a', J: '#eeece4', j: '#c9c6bb', V: '#1f5a46' } },
  lab: { torso: 'hoodie', phones: true,
    pal: { B: '#6b6b76', b: '#50505a', w: '#e6e6ea', P: '#3a3a44', p: '#2a2a32', l: '#4c4c58', O: '#e7e2d8', n: '#bdb7aa', N: '#8a8aa0' } },
  gym1: { torso: 'tank', shorts: true, sleeve: { B: 'S', b: 's', r: 'S' }, armOutline: 's',
    pal: { B: '#2a2a33', b: '#1c1c22', P: '#4b4b58', p: '#383843', l: '#5e5e6c', O: '#e7e2d8', n: '#c84a3a' } },
  gym5: { torso: 'tankBig', shorts: true, bigArms: true, armOutline: 's',
    pal: { B: '#2a2a33', b: '#1c1c22', P: '#4b4b58', p: '#383843', l: '#5e5e6c', O: '#e7e2d8', n: '#c84a3a' } },
  phd: { torso: 'phd', skirt: 'phd', sleeve: { B: 'B', b: 'b', r: 'K' }, hats: ['tam'], tassel: 'V',
    pal: { B: '#1f5a46', b: '#16463a', r: '#2e7a60', K: '#121214', V: '#e2b84a', P: '#24242c', p: '#18181e', l: '#33333d', O: '#1a1416', n: '#3a2c2c' } },
  work: { torso: 'sunhood', hood: true,
    pal: { B: '#6c4fb6', b: '#4d378c', r: '#8a6fd2', z: '#c9bdf0', P: '#24252c', p: '#18191e', l: '#363844', O: '#ece8df', n: '#bdb7aa' } },
  hunt: { torso: 'blazer', camo: true, hats: ['cap'],
    pal: { B: '#5d5b3c', b: '#3f3e29', r: '#7b7450', T: '#2c2b22', P: '#8a7b5a', p: '#6c5f44', l: '#a3936d', O: '#4a3324', n: '#6a4a34', J: '#ff6b1a', j: '#c94e0f' } },
  forage: { torso: 'hoodie', hats: ['beanie'], props: [['hand', 'basket', -3, 1]],
    pal: { B: '#5d6b3e', b: '#434e2c', w: '#5d6b3e', P: '#6a6052', p: '#504839', l: '#827766', O: '#5a3b2a', n: '#7a5440', J: '#a5532e', j: '#7d3c20', V: '#a5532e', M: '#9a6b3a', m: '#7a5028', x: '#7a5028', Z: '#f0a830', z: '#d07a18' } },
  fish: { torso: 'vest', sleeve: { B: 'T', b: 't', r: 'T' }, hold: true, hats: ['bucket'], props: [['rod', null, 0, 0]],
    pal: { B: '#a8996e', b: '#857852', t: '#4c4f5a', T: '#5f6370', P: '#4c4f5a', p: '#393b44', l: '#60636f', O: '#3a2c24', n: '#5a463a', J: '#c2b088', j: '#9a8a64' } },
  tide: { torso: 'bib', sleeve: { B: 'T', b: 't', r: 'T' }, props: [['hand', 'bucket', -3, 1]],
    pal: { B: '#3b5a44', b: '#2b4232', T: '#c9c2b4', t: '#a39c8e', P: '#3b5a44', p: '#2b4232', l: '#4f7259', O: '#2a3a2e', n: '#3b5a44', M: '#3a7fc4', m: '#2a5f96', x: '#20232b', Z: '#6b3f8f', z: '#4a2a66' } },
  scuba: { torso: 'wetsuit', sleeve: { B: 'B', b: 'b', r: 'B' }, mask: true, fins: 4, stand: true, props: [['back', 'tank', 2, 16]],
    pal: { B: '#1d2028', b: '#121418', r: '#2f74c0', P: '#1d2028', p: '#121418', l: '#2c3240', O: '#16181e', n: '#2f74c0', V: '#e8b923', v: '#b88d14', x: '#3a3a40', F: '#1d2028' } },
  freedive: { torso: 'wetsuit', camo: true, sleeve: { B: 'B', b: 'b', r: 'B' }, hold: true, mask: true, snorkel: true, fins: 9, stand: true, props: [['gun', null, 0, 0]],
    pal: { B: '#3e4a36', b: '#2a3326', r: '#3e4a36', P: '#3e4a36', p: '#2a3326', l: '#55634a', O: '#2a3326', n: '#55634a', F: '#2a3326', x: '#16181e' } },
};
export const OUTFIT_KEYS = Object.keys(OUTFITS);

const CAMO = ['BrbB', 'bBBr', 'rBbB', 'BBrb'];
const SCARF = [[6, 16, 'L'], [7, 16, 'Q'], [8, 16, 'L'], [9, 16, 'Q'], [10, 16, 'L'], [11, 16, 'Q'],
  [10, 17, 'L'], [11, 17, 'Q'], [11, 18, 'L'], [11, 19, 'Q'], [11, 20, 'L']];
const MASK = [[12, 8, 'k'], [13, 8, 'k'], [14, 8, 'k'], [15, 8, 'k'], [16, 8, 'k'], [17, 8, 'k'], [18, 8, 'k'],
  [12, 9, 'k'], [13, 9, 'g'], [14, 9, 'a'], [15, 9, 'a'], [16, 9, 'E'], [17, 9, 'a'], [18, 9, 'k'],
  [12, 10, 'k'], [13, 10, 'a'], [14, 10, 'a'], [15, 10, 'a'], [16, 10, 'E'], [17, 10, 'a'], [18, 10, 'k'],
  [12, 11, 'k'], [13, 11, 'k'], [14, 11, 'k'], [15, 11, 'k'], [16, 11, 'k'], [17, 11, 'k'], [18, 11, 'k'], [19, 11, 'k']];
const HAND = { mid: [7, 22], fwd: [9, 22], back: [6, 22], hold: [11, 20], curlDown: [7, 22], curlUp: [10, 18], none: [8, 18] };
// Poses as frame lists of [legs, arm, bob, bare]. Walk contact frames sit 1px lower. `cheer` is
// the cap toss: feet planted, bouncing, and bareheaded, because the hat is in the air. `type` sits
// with the hands forward on a keyboard, nodding; `curl` lifts a dumbbell from the hip to the chest.
// `hang` is for pull-ups: the arm is left off, because the scene draws both arms up to the bar
// behind the head; its hand is the shoulder, where those arms start.
const POSES = {
  walk: [['near', 'back', 1], ['pass', 'mid', 0], ['far', 'fwd', 1], ['pass', 'mid', 0]],
  sit: [['sitA', 'mid', 0], ['sitB', 'mid', 0]],
  cheer: [['stand', 'fwd', 1, true], ['stand', 'mid', 0, true]],
  type: [['sitA', 'hold', 0], ['sitA', 'hold', 1]],
  curl: [['stand', 'curlDown', 0], ['stand', 'curlUp', 0]],
  hang: [['stand', 'none', 0], ['pass', 'none', 0]],
};
export const SEAT_Y = 38;             // sit pose: the outline row under the thighs rests on the ledge
const HAIR_UNDER_HAT = new Set(['H', 'h', 'k', 'f']);

// Clear hair/outline above the hat's top edge in each column, then stamp the hat.
function stampHat(c, hat, x0, y0) {
  const g = parseRows(hat), tops = new Map();
  g.forEach((row, y) => { for (let x = 0; x < row.length; x++) if (row[x] !== '.' && !tops.has(x)) tops.set(x, y); });
  for (const [x, ty] of tops) for (let yy = y0 - 3; yy < y0 + ty; yy++) if (HAIR_UNDER_HAT.has(c.get(x0 + x, yy))) c.set(x0 + x, yy, '.');
  c.stamp(g, x0, y0);
}

// Headphone band: the first opaque pixel (and the one below it) in columns 5..15.
function headphones(c, x0, y0) {
  for (let x = x0 + 5; x < x0 + 16; x++) {
    for (let y = y0 - 2; y < y0 + 12; y++) if (c.get(x, y) !== '.') { c.set(x, y, 'N'); c.set(x, y + 1, 'N'); break; }
  }
}

function palette(o) {
  const pal = { ...BASE_PALETTE, ...PROP_DEFAULTS, ...o.pal };
  if (o.mask) { pal.a = '#bfe3f2'; pal.g = '#ffffff'; }
  return pal;
}

function frame(o, [legsKey, armKey, bob, bare = false]) {
  if (o.stand) { legsKey = 'pass'; armKey = 'mid'; }
  if (o.hold) armKey = 'hold';
  const props = o.props || [];
  const c = new Grid(SPRITE_W, SPRITE_H), X = OX, Y = OY;

  for (const [kind, part, dx, dy] of props) {
    if (kind === 'back') c.stamp(PROP[part], X + dx, Y + dy + bob, { outline: 'k' });
    if (kind === 'umbrella') {
      c.stamp(PROP[part], X + dx, Y + dy + bob, { outline: 'k' });
      line(c, X + 12, Y + dy + 6 + bob, X + 12, Y + 19 + bob, 'x');
    }
  }

  let legs = o.stand ? LEGS.stand : LEGS[legsKey];
  if (o.shorts) legs = recolor(legs, { P: 'S', l: 'S', p: 's' }, 3);
  c.stamp(legs, X, Y + 25, { outline: 'k' });
  if (o.fins) {
    for (let y = 0; y < c.h; y++) for (let x = 0; x < c.w; x++) {
      if ((c.px[y][x] === 'O' || c.px[y][x] === 'n') && y >= Y + 31) {
        for (let k = 1; k <= o.fins; k++) if (c.get(x + k, y) === '.') c.set(x + k, y, 'F');
      }
    }
  }
  if (o.skirt) c.stamp(SKIRT[o.skirt], X, Y + 25 + bob, { outline: 'k', over: true });

  c.stamp(T[o.torso], X, Y + 17 + bob, { outline: 'k' });
  if (o.scarf) for (const [x, y, col] of SCARF) c.set(X + x, Y + y + bob, col);
  if (o.camo) {
    for (let y = Y + 17 + bob; y < Y + 25 + bob; y++) for (let x = 0; x < c.w; x++) {
      if (c.px[y][x] === 'B' || c.px[y][x] === 'r') c.px[y][x] = CAMO[y % 4][x % 4];
    }
  }
  if (props.some(([kind, part]) => kind === 'back' && part === 'backpack')) {
    for (const dy of [17, 18, 19]) c.set(X + 9, Y + dy + bob, 'm');     // shoulder strap
  }
  if (o.hood) c.stamp(HOOD, X + 3, Y + 15 + bob, { outline: 'k' });

  if (armKey !== 'none') {
    let arm = o.bigArms ? ARM_BIG[armKey] : armKey === 'hold' ? ARM_HOLD : ARMS[armKey];
    if (o.sleeve) arm = recolor(arm, o.sleeve);
    c.stamp(arm, X, Y + 18 + bob, { outline: o.armOutline || 'b', opaqueOnly: true });
  }
  const hx = X + HAND[armKey][0], hy = Y + HAND[armKey][1] + bob;

  for (const [kind, part, dx, dy] of props) {
    if (kind === 'hand') c.stamp(PROP[part], hx + dx, hy + dy, { outline: 'k' });
    if (kind === 'camera') {
      c.stamp('xx\nxx', X + 11, Y + 20 + bob, { outline: 'k' });
      c.set(X + 12, Y + 20 + bob, 'g');
      line(c, X + 8, Y + 17 + bob, X + 11, Y + 20 + bob, 'x');
    }
    if (kind === 'gun') {
      line(c, hx - 2, hy, hx + 17, hy, 'M');
      line(c, hx - 2, hy + 1, hx + 6, hy + 1, 'm');
      c.set(hx + 18, hy, 'g'); c.set(hx + 19, hy, 'g');
    }
  }

  c.stamp(HEAD, X, Y + 1 + bob, { outline: 'k', over: true });
  if (o.mask) {
    c.stamp(parseRows(FACE).map(r => r.replace(/[GgE]/g, '.')), X, Y + 1 + bob);
    for (const [x, y, col] of MASK) c.set(X + x, Y + 1 + y + bob, col);
    for (let x = 4; x < 12; x++) c.set(X + x, Y + 1 + 9 + bob, 'k');      // strap
  } else {
    c.stamp(FACE, X, Y + 1 + bob);
  }
  for (const [kind] of props) {
    if (kind === 'rod') {
      line(c, hx + 1, hy, hx + 16, hy - 20, 'x');
      line(c, hx + 16, hy - 19, hx + 16, hy - 6, 'g');
      c.set(hx + 2, hy + 1, 'x'); c.set(hx + 3, hy + 1, 'x');
    }
  }
  if (o.snorkel) {
    for (let y = -4; y < 3; y++) c.set(X + 5, Y + 1 + y + bob, 'x');
    c.set(X + 6, Y + 1 - 4 + bob, 'x');
  }
  if (!bare) {
    for (const hat of o.hats || []) stampHat(c, HAT[hat], X, Y + bob - (hat === 'mortar' || hat === 'tam' ? 1 : 0));
    if (o.pom) c.stamp(POM, X, Y - 2 + bob);
    if (o.tassel) for (let y = 0; y < 6; y++) c.set(X + 16, Y + y + bob, o.tassel);
  }
  if (o.phones) {
    headphones(c, X, Y + 1 + bob);
    c.stamp('NNN\nNNN\nNNN\nNNN', X + 4, Y + 1 + 8 + bob, { outline: 'k', over: true });
  }
  c.outlineAll('k');
  return c.rows();
}

// One outfit in one pose ('walk': 4 frames, the others 2), plus what the engine needs to place it.
// hands: per frame, the [x, y] in the sprite where props such as a dumbbell are held.
export function heroSprite(key, pose = 'walk') {
  const o = OUTFITS[key];
  if (!o) throw new Error(`unknown outfit: ${key}`);
  if (!POSES[pose]) throw new Error(`unknown pose: ${pose}`);
  const hands = POSES[pose].map(([, arm, bob]) => {
    const a = o.hold ? 'hold' : o.stand ? 'mid' : arm;
    return [OX + HAND[a][0], OY + HAND[a][1] + bob];
  });
  return { frames: POSES[pose].map(p => frame(o, p)), palette: palette(o), width: SPRITE_W, height: SPRITE_H, anchorX: ANCHOR_X, footY: FOOT_Y, seatY: SEAT_Y, hands };
}
